### ISSUE TITLE
Support non-ctranspose-invariant sdpvar matrices

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#103]
The sdpvar objects created by the class CommutantVar are by default invariant under transposition. The reason being that in the context of SDP, a PSD matrix is necessarily transpose-invariant. In a more general context it might be useful to allow for the construction of matrices which are invariant under a group action, but not under transposition.

**Comment by denisrosset** [comment]
Is this transpose invariance, or conjugate-transpose invariance?

Then, there is the issue of using the commutant in the context of SDP computations: SDP matrices transform under `A X A'`, not `A X inv(A)` . This is the same when representations are unitary, but when we lose unitary, the distinction is important.

Is the support for nonunitary representations important? I'd say yes: for example, NPA hierarchy problems in the Collins-Gisin representation correspond to nonunitary representations, and we may want to support that.

The question of using `transpose` instead of `conjugate transpose` supposes that CommutantVar is real valued. I guess we want to not only support different real representation types (R, C, H), but also complex-valued matrices #101

**Comment by jdbancal** [comment]
I'ld say we're talking in general about complex transposition here (corrected the title). Is this a problem for nonunitary representations? What is needed there: transposition of complex transposition?

**Comment by denisrosset** [comment]
On the SDP side, `ctranspose` is the correct terminology. In RepLAB however, the use of the `Commutant` makes sense only for unitary representations.

Let's assume unitarity for now. Nonunitary is a bag of worms that I don't want to open now (but I'm keeping it in mind for the future!)
