### ISSUE TITLE
How do we mention method names?

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#143]
Currently, in the documentation, we repeat the function application.

It's clear how we document stand-alone functions (not part of a class).

For static methods, I suggest that we add the fully qualified class name:

```matlab        
        function domain = lambda(header, eqvFun, sampleFun)
        % lambda - Constructs a domain from function handles
        %
        % domain = replab.Domain.lambda(header, eqvFun, sampleFun)
```

For non-static methods, I suggest that we use an instance variable other than `self`, and use modern OO calling convention:

```matlab
        function b = eqv(self, t, u)
        % eqv - Tests domain elements for equality/equivalence
        %
        % b = obj.eqv(t, u)
```

(currently we have `% b = eqv(self, t, u)` which is not super descriptive)

In any case we should update the API documentation style guide with the answers to the above cases.

**Comment by jdbancal** [comment]
Ok, so I think from our previous discussions we already agreed to use the fully qualified class name, and this is already documented in `api_documentation_style.md`. So do I understand correctly that you are suggesting a change for non-static methods?

My impression is that you are trying to deal with the fact that the name of the first argument `self` is not very user-friendly (it is more a programmer's convenience, since it tells about the code structure of the class, than a user convenience). So you propose to avoid the appearance of `self`. Is this correct?

**Comment by denisrosset** [comment]
1. Yes indeed the style guide mentions fully qualified class names, it's just that the current `replab.Str` class was updated in the same PR with a different style. My bad.

The two other points below refer to non-static member methods only. And in my mind, the API documentation describes the code as used from the outside (I don't expect many users to actually subclass our types). There are three points.

2. The `self` argument hints at how the parameter is used inside the method body. I suggest using renaming it `obj`, or a shorthand version of the object type like `grp` or `rep`.

3. For nonstatic members, the line `% suite = matlab.unittest.TestSuite.fromMethod(testclass, testmethod, [varargin])` is not a valid member call, but it looks like a valid static call.

4. For abstract classes, the line ` z = replab.Group.compose(self, x, y)` refers to a method that is not implemented (as compared to `z = replab.PermutationGroup.compose(self, x, y)`). And we'll pull the parent API documentation when asking for help about an inherited subclass method.

**Comment by jdbancal** [comment]
What I don't like with using `obj` as a first argument of non-static methods is that this does not tell us the class to which this method belongs... There can be many classes with a static method called `lambda`, and doing help of one particular lambda will tell us the lambda from which class we are having, because lambda is a static method in the above example. There can also be several classes with a non-static method called `eqv`, but with the above syntax, doing a help on this method will not show the class on which this particular `eqv` method applies. (Previously I understood that this was one of the main motivation to add the fully qualified name to methods)

I agree that Matlab is not happy with calling a non-static method with a fully qualified name, but it seems the following works: `eqv(replab.bsgs.TrivialGroup)` calls the method `replab.bsgs.TrivialGroup`. Of course, that's because `replab.bsgs.TrivialGroup` can be constructed without arguments, but in general all arguments of a function must be constructed properly before calling the function. So what would you think of documenting the `eqv` method in class `replab.something` as follows:

```matlab
        function b = eqv(self, t, u)
        % eqv - Tests domain elements for equality/equivalence
        %
        % b = eqv(replab.something, t, u)
```

Or any other suggestion?

**Comment by denisrosset** [comment]
Indeed, it's cool to fully qualify the static `lambda` as it belongs to a single class, and call be called directly using the syntax we display in `help`. No issues there.

Now, moving to non-static methods. `eqv` is defined in `replab.Domain`, but `Domain` can't be instantiated. However, when we call `help` on say a permutation group, we'll get the help for a `Domain` instance, which is displayed on the screen. Or the `compose` method which is documented at the `Monoid` level. A lot of the methods in RepLAB are abstract, so it's not a one time problem.

The thing is, we have an `eqv` method in `replab.Domain`, but also in `replab.Monoid`, `replab.Group`, `replab.FiniteGroup`, `replab.NiceFiniteGroup`, `replab.PermutationGroup` which are all abstract. 

Fun fact: `replab.PermutationGroup` implements the `eqv` method from `replab.Domain`, but `replab.PermutationGroup` is an abstract class itself! Only the subclasses `replab.Permutations` and `replab.PermutationSubgroup` can be instantiated.

So where do we put documentation for `eqv`? Right now, I was thinking of `replab.Domain.eqv` only. Should we duplicate that documentation in all the subclasses? (Thinking of 20+ copies to keep synchronized in the case of a typo, etc.) If we document `eqv` in `replab.Domain`, what syntax do we use?

**Comment by denisrosset** [comment]
I guess that's the time we should prototype the proposed solutions and see what happens when we call `help` on the various subclasses, how it affects Sphinx etc.

**Comment by jdbancal** [comment]
I wonder if we are not mixing a bit too many elements right from the beginning of the discussion here: even focusing only on non-static methods,
1. There are class methods which are abstract (or which implement inherited abstract classes)
2. There are also class methods which are not abstract

Moreover, among abstract methods or implementations of inherited abstract methods:
1. 1) There are inherited abstract methods which have their own documentation (the documentation can include some description of the implementation, which could be different for different instantiations of an abstract method)
    2) There are inherited abstract methods which don't have their own documentation (hence inherit the documentation from their abstract method's)

I see that you suggest not using 1.i. at all, but I don't see here a discussion of case 2. should we also not use them? Requesting the documentation of class methods to be of a given format imposes this format not only for abstract classes, but for all cases above. Hence, it seems to me that a guideline should be suited to all possible cases.

Maybe one way forward could be to first define what would be the ideal documentation style for each of these cases independently, and only try to come up with a general rule after we have already discussed each of these cases?

**Comment by denisrosset** [comment]
I'll define a subset of the RepLAB classes that exhibits the variety of cases above, document them using the current style guide. Then we will have a better idea of the shortcomings.

I agree that indeed, we could have an abstract method having other documentation at implementation point, so yeah `1.i` can happen.

**Comment by denisrosset** [comment]
Information has been updated in the API guide.
