### ISSUE TITLE
In `replab_init`, log the installation of SDPT3 when `verbose >= 1`

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#163]

**Comment by jdbancal** [comment]
Hmm, in which case is the log of SDPT3 not displayed? Currently, whenever `install_sdpt3` is called, its output is presented to the user... (which actually is too much information when e.g. verbose=0)

**Comment by jdbancal** [comment]
So I tried to tidy up the output of SDPT3. To me, this seems to require displaying less log rather than displaying more of it. Changes are in https://github.com/replab/replab/commit/304ffe7794b2281b5fc691bfe0e08c9d32e92d82 .

This also deals with situations in which we bump into an incompletely compiled SDPT3 folder.

**Comment by jdbancal** [comment]
@denisrosset are you happy with the current solution?

**Comment by denisrosset** [comment]
Yes.
