### ISSUE TITLE
Do we want to include the infrastructure code in the coverage?

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#201]
Infrastructure code plays a special role. For instance, the file `replab_init` is mostly meant to be called just once, and it lies outside of the `src` folder, which is monitored for coverage.

Should we test these functions? E.g. should we test the code required to run the tests?

**Comment by denisrosset** [comment]
I'd exclude all the `replab_*.m` files. They are actively used as part of the release process, so any bugs will quickly surface.

MOCov has a `-cover_exclude`  option for this.

**Comment by jdbancal** [comment]
Sure, I can do that, but the infrastructure has much more code, c.f. `replab.infra`. Do we want to cover this as well? The point is that some of these files, such as `help` rely on `replab_init` being run in the parent directory. If we want to monitor these files in `replab.infra`, we'ld need to do something more intricate (just excluding `replab_init.m` probably won't work)

**Comment by denisrosset** [comment]
A lot of the files in `replab.infra` can actually be tested; most of the code is used to parse Matlab source files, and I already wrote 1-2 tests for them.

Once we have an exclusion mechanism, I'll update the list as we go (stuff under `+replab.+compat` can't be fully covered as well, because of the giant `if` that has Octave and Matlab branches!).

**Comment by jdbancal** [comment]
#204 Brings exclusion of `replab_*.m` files in the code coverage.

**Comment by denisrosset** [comment]
Looks good! thanks
