### ISSUE TITLE
Guzzle Sphinx theme has small width on big monitors

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#202]
The current theme looks great on mobile and laptop screens, but for larger monitors, exhibits the behaviour discussed in

https://github.com/readthedocs/sphinx_rtd_theme/issues/295

Should we change anything about it? What are the best practices of other projects?

Pinging @jdbancal as this was discussed over Skype

**Comment by jdbancal** [comment]
Apparently, this is a known issue. Not sure what timescale they have in mind at readthedocs for implementing https://github.com/readthedocs/sphinx_rtd_theme/issues/295#issuecomment-456231694, but since we rely on their theme, we can rely on their solution as well!

Meanwhile, if we want to avoid the problem to first order we could implement the quick fix mentioned in this thread which redefines the max width. I guess this would address the problem in the mean time. What do you think?

**Comment by denisrosset** [comment]
We can try that for sure! if we do these tests early, we can fine comb the documentation pages (as we intended to do anyway) and see if it really works.

On my side, I tend to only have a half-screen browser page open, so the width is not really an issue.

**Comment by denisrosset** [comment]
Related issue #207

**Comment by denisrosset** [comment]
I've checked the theme on a variety of devices and it looks pretty clean. @jdbancal , do you have a Mac computer to try things on? Then we can close that issue.

**Comment by jdbancal** [comment]
Great! I don't have a mac... but don't mind if the issue is closed given that it works already elsewhere
