### ISSUE TITLE
Doctests: REPL output is inconsistent across Matlab versions

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#252]
@smygdala ran the tests on Matlab 2016a, and this Matlab version does not enclose strings with spaces with quotes when displaying them on the REPL output.

This breaks the doctests.

**Comment by jdbancal** [comment]
Thanks for reporting this! Unfortunately, I don't have a copy of 2016a around to try it out. Would it be possible to have some more information about this situation? E.g.:
 - What is the error message?
 - When you say that Matlab does not enclose strings with spaces, I suppose this happens when calling a specific function on the string. Which function is it: `disp`, `sprintf`, ...?

**Comment by denisrosset** [comment]
We moved to a different doctest system already.
