### ISSUE TITLE
RepLAB is incompatible with existing overloads of the help function

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#257]
For example, it doesn't work well with the [matlab-emacs](https://sourceforge.net/projects/matlab-emacs/) package, which shows, in the help window
```
MATLAB Emacs help override recursion detected.  Exiting.
```

**Comment by jdbancal** [comment]
I see what is happening: each library is redirecting help that doesn't concern itself to the `help` function that appears in the path when they remove themselves. Hence, if there are two such libraries on top of Matlab in the path stack, they will reference each other, thus creating a loop never reaching matlab's `help` function.

One way to fix this on our side would be to not assume that the next `help` must be Matlab's one, but to rather explore the path stack and decide which `help` function looks more like Matlab's original one... Doing this by folder name seems quite unpredictable given the variety of possible setups. However a signature might be obtained from the file contents:

Matlab's help file contains the line
```
%   Copyright 1984-2019 The MathWorks, Inc.
```
and Octave's help file contains
```
## This file is part of Octave.
```
Naturally, this would still assume that no other package decided to copy past one of these files in their own code...

Ideally, `matlab-emacs` should be changed accordingly, otherwise they'll also expose the same error with other libraries, but that's out of our scope.

**Comment by jdbancal** [comment]
Actually, looking for matlab's original help function would clearly avoid loops, but it could also blind some libraries: if `replab` comes before `matlab-emacs` in the path, matlab-emacs' help function will never be called since matlab's own `help` function will be called instead.

A more scalable solution would be to allow a `help` call to visit successively all instances of `help` according to the path priority (until one instance accepts the call of course). Note that this is not the logic used by `matlab-emacs`, which rather assumes that it it the first `help` function appearing in the path stack, hence the bug... (we could report it of course). @denisrosset Do you think it would be good to follow that more scalable logic? Or would you prefer if we bypass any other library and redirect directly to matlab's original `help` command?

Note that both logic would still lead to manageable solutions without changing `matlab-emacs`' code if we make sure `matlab-emacs` appears first in the path (and no third library also overloads the `help` function in a way similar to `matlab-emacs`, otherwise the two libraries will already have a conflict between themselves).

**Comment by denisrosset** [comment]
I'm going for the following.

Matlab has a `which` commands that can return all files implementing a function, even the ones being shadowed. `which` needs the `-all` argument for that

Octave doesn't have that, but we can inspect every path element to check if there is a `help.m` present.

Then:

- If one copy of help is present, we get a function handle of it
- If the emacs stuff is present in addition to the original help, we bypass it and implement it ourselves. We grab a handle of the original Matlab/Octave function.
- If other stuff is present, we do not add our version of "help.m" to the path. I'll make a copy with the name `replab_help` in that case.

Another thing: by caching function handles to the original help function, we do not need path trickery in our help anymore.

**Comment by jdbancal** [comment]
Do you mean you want to make replab taylor to emacs specificities (in the sense that it would treat `emacs-matlab` differently than other libraries potentially overloading the `help` function)?

**Comment by denisrosset** [comment]
In that case, we know that we can safely bypass it, because its functionality is minimal. In other cases, the user should make an informed choice (by removing the other help overloads).

**Comment by jdbancal** [comment]
I see, not sure it's our job to implement the emacs code in our own, though. This would be code duplication with its shortcomings (e.g. if it gets updated one day it won't be on our side). Bypassing would be safe indeed, I let it for you to choose what you think is best.

Also remember we said we wanted to support the case in which another instance of replab is already in the path. That would be a case in which "another help function is also in the path", but we shouldn't rename anything in this case. Rather, in this case we produce an error.

**Comment by denisrosset** [comment]
PR incoming! Thanks for the comments, they have all been handled.

I put matlab-emacs support as a special case (it's a few lines of code); and am detecting the original Matlab/Octave functions using their paths rather than by inspecting content. I guess it's ok
