### ISSUE TITLE
Links not present in Matlab's own help

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#357]
It seems that since we capture the help text from matlab/octave, and print it ourselves, links are not available anymore (except for help on our own methods, which we manage well). For instance `help times` returns
```
>> help times
 .*  Array multiply.
    X.*Y denotes element-by-element multiplication. X and Y must have
    compatible sizes. In the simplest cases, they can be the same size or
    one can be a scalar. Two inputs have compatible sizes if, for every
    dimension, the dimension sizes of the inputs are either the same or one
    of them is 1.
 
    C = TIMES(A,B) is called for the syntax 'A .* B' when A or B is an
    object.
 
    See also MTIMES.

    Documentation for times
       doc times
```
which suggests to have a look at `mtimes`'s documentation, but the corresponding text is not clickable.

**Comment by denisrosset** [comment]
Ouch!

also other bug: calling `help` without an argument errors.

We should, in the case our own help was called without output arguments

1) capture the original help output only if we're doing something else with it (emacs for example)

2) call the original help without output arguments otherwise

What a rabbit hole!

**Comment by jdbancal** [comment]
Oh, good catch for help without any argument.
Yep, that sounds like a good strategy. We're getting there!
