### ISSUE TITLE
Why do we test for the presence of SDPT3 if there is not decent solver in path?

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#406]
When we do the test here:
https://github.com/replab/replab/blob/46412cd9e58178cdc2d5b9bc08a38198021e38df/src/%2Breplab/%2Binit/initSDP.m#L42
it means that YALMIP either does not have a SDP solver in the path, or is using LMILAB.
Thus why test for the presence of SDPT3? Shouldn't we perform the test after the installation of SDPT3 then?

**Comment by jdbancal** [comment]
I guess what you mean is that if no decent solver was found, then we would expect `sedumi` not to be found also (and hence it is not needed to test for it).

I think it is important to check for the existence of `sedumi` in the path before adding it to the path for the same reason that we test for the existence of `yalmip` in the path before adding it to the path: because there could be a different copy already put in the path by the user (possibly with a different version), and we do not want to overwrite it with ours. This could have unexpected side/effects which are hard to track down (e.g. in a user program totally unrelated to RepLAB), and it is worth trying to avoid if possible. In particular, I wouldn't assume that if yalmip chose 'LMILAB' as its preferred solver, then this implies sedumi should not be in the path. This statement depends on the preferences of yalmip: it is currently true, but it may change in the future independently of our control. Checking for the presence of some version of sedumi in the path avoid any trouble if this should happen, and is easy to do explicitely.

Now what you are suggesting is to test for the proper installation of sedumi after having added it to the path. This is a different thing which is also possible, and which we do not do at the moment, even for other components such as yalmip, MOCov, MOxUnit, etc. It could be added.

**Comment by denisrosset** [comment]
Ok, that makes sense! we still have, as a failure mode, the possibility that SDPT3 (not sedumi, right?) is in the path, but for some unknown reason Yalmip selects LMILAB.

I'll adapt the new code based on this insight, and will keep the check.

**Comment by jdbancal** [comment]
Yes, sorry, I meant SDPT3

**Comment by johanlofberg** [comment]
If LMILAB is selected by YALMIP, it means neither sedumi nor sdpt3 is in the path. LMILAB is a worst-case last resort all bets are off selection.

**Comment by jdbancal** [comment]
Another reason why things were done in this order is that a solver might be in the path, but have an outdated license. In this case, yalmip detects it all right, but we cannot solve anything (things fail when calling the solver). This is another instance in which we have 'no decent solver in path', because the very good solver which is in the path has no use.

Currently, when this happens, RepLAB refuses to work, exiting with the message:
```
Dependency sdpt3 available in path, but not working properly
```

What we want to do instead, is activate our version of SDPT3 here, so that at least the unit tests can be run. This will not affect the user, because if he/she still uses the other solver in his/her code, it will still fail (hence he/she can discover that the license is outdated by debugging one's own code, not blaming RepLAB). For this, we need to check whether a solver is present (and working) or not independently of whether it is SDPT3 or not. I'll do that through another dedicated class like `replab.init.existingSDPSolver`.
