### ISSUE TITLE
`backtrack.test` function never called during backtrack

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#451]
When applying the backtrack algorithm on a trivial element with no symmetry as in
```
n=4
replab.S(n).vectorStabilizer([1:n])
```
the testing function `replab.bsgs.OrderedPartitionStabilizer.test` is never called.

Only the proposition function `replab.bsgs.OrderedPartitionStabilizer.prop` is called to test fully defined tentative permutations. Therefore, we do not take advantage of knowing that a whole set of permutations will never work early on, and we explore large sets of permutations we could readily exclude. In this particular example, since no permutation is invariant here (except the identity), the whole of `factorial(n)-1` permutations are tested one by one. Obviously, this is quickly prohibitive when `n` is more than a handful (n=8 takes 1 sec, n=9 takes 9 sec, n=10 probably ~90sec).

Is there a reason we don't call the test method in this case?

**Comment by denisrosset** [comment]
@jdbancal Because in that case, the blocks of size 1 should have already shown that the subgroup is trivial. However, the current code was lacking the handling of those blocks of size 1; this is now corrected.

At the same time, the fix exposed a bug in `PermutationGroup.pointwiseStabilizer` which is now fixed.
