### ISSUE TITLE
Graph.connectedComponents does not respect Partition invariants

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#525]
Each block in a partition should have its indices sorted in ascending order; the blocks themselves are sorted by their minimal index, in ascending order.

However, `Graph.connectedComponents` calls the `replab.Partition` constructor directly instead of the `Partition.fromBlocks` method. With Marie, we just observed a case where `.connectedComponents` returns a partition with one block and the indices not sorted.

This can be solved in two ways:

- always call the static method `.fromBlocks`, which reorders blocks and indices,
- make sure the algorithm returns blocks in the sorted order.

**Comment by denisrosset** [comment]
```
>>> A = [0 0 0 0; 0 0 1 1; 0 1 0 1; 0 1 1 0]
>>> G=replab.UndirectedGraph.fromAdjacencyMatrix(A)
>>> G.connectedComponents
ans = 
Partition '|234|1'
blockIndex: [3, 2, 2, 2]
    blocks: {1 x 0 empty double array, [2, 3, 4], 1}
         n: 4
```

**Comment by jdbancal** [comment]
My apologies, I did not notice the following comment in Partition.m:
https://github.com/replab/replab/blob/42e8824cb9641e4f1fe7b9936c97c4ba5587a5fb/src/%2Breplab/Partition.m#L4-L5
I'll fix this.

I agree that calling `Partition.fromBlocks` instead of the `Partition` constructor would be a possible solution, but do you think it is ok to call the constructor if we ensure (and document) that the conditions are met? This would make things more efficient for large graphs, but maybe we prefer to guarantee robustness... let me know what you think @denisrosset
