### ISSUE TITLE
Finish documentation RepLAB classes/functions

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#56]
This tracks the progress of minimally documenting RepLAB using Sphinx conventions.

- [ ] replab.SignedPermutationGroup is partially documented

- [x] replab.directproduct.* is not documented

- [ ] replab.Permutations is partially documented

**Comment by jdbancal** [comment]
Since the discussion moved here, let me answer https://github.com/replab/replab/issues/10#issuecomment-523685546 here.

In #52 we agreed to make rendering of help in Matlab (through the `help` function) a priority over the constraints imposed by Sphinx and now it is proposed to treat the Sphinx documentation as a primary resource and the `help` command as a secondary consideration. @denisrosset How would you suggest to proceed to fulfil both of these requirements?

**Comment by denisrosset** [comment]
We did actually incorporate Sphinx!
