### ISSUE TITLE
Use of sparse matrices in RepLAB

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#94]
Right now, (un)signed permutation representations use the generic RepByImages construction. And we recently switched to nonsparse matrices by default. Together, this makes things like `ComplexReflectionGroupTest` much much slower.

1) Should we switch on sparse matrices for the tests? How do we test the sparse and nonsparse paths?

2) Or I could introduce a special Rep subclass for permutation representations.

**Comment by denisrosset** [comment]
@jdbancal This is kind of a delicate issue where user friendliness, code complexity and speed intersect.

**Comment by jdbancal** [comment]
Why should the sparse / non-sparse option affect the working of the library? Was this not meant to be a user interface option?

**Comment by denisrosset** [comment]
It affects how floating point matrices in RepLAB are stored. When the flag is on, speye is called instead of eye, etc.

Note that when the flag is on, sparse matrices are used whenever it makes sense only, not everywhere.

Motivation : Beginners where super confused when a sparse matrix was returned and displayed in the console.

I'd be happy to put sparse matrices on by default and remove the flag if somehow we can control how matlab/octave display small sparse matrices

**Comment by jdbancal** [comment]
I don't think we should compromise code quality for user display: ideally, those two should be independent from each other. If we want to please users you wish not to see any sparse output in their display, then this should not forbid us from performing computations the way we think is better (for everyone, including them when they'll start to push the library). Maybe one way to achieve that could be to use the flag only at display time to force printing `sparse` arrays in their `full`version?

Potentially, this could also simplify the core code since it won't have to deal with multiple potential encodings of the same objects... and also avoid having to test the library in two different regimes as you say

**Comment by denisrosset** [comment]
I'm thinking of ways around the problem, and start to think that this sparse flag is not healthy in the code base. Simplicity simplicity simplicity

The problem of using full matrices "at display stage" is that we have no way to control Matlab display of sparse matrices, and we expect users to call "Rep.image" directly.

Now, I'm thinking of: having methods return dense matrices, always. But in inner computations, we already use more specific methods (like asking Rep to act on a vector or matrix directly without forming the representation image). By specializing Rep to handle sparse representations better (as in signed or unsigned permutations, etc...), we get the best of both worlds.

**Comment by denisrosset** [comment]
Alternative: trigger the use of sparse matrices when the dimension is big enough. Then tutorials won't be affected as they use small examples.

**Comment by jdbancal** [comment]
I fully agree about going for simplicity :) In this regard, maybe if we can do without triggering different behaviors depending on the size if would be better... In fact, before getting there, we could also consider adding a tutorial on the website about sparse matrices and how to deal with them so that users can tame them and at the same time learn something generally useful...

Right, unfortunately Rep.image can only return one type of object and there doesn't seem to be a matlab option for printing all sparse matrices as full...

Actually, there would be a way for Rep.image to know whether it's going to provide its result to a user or to another function, but that wouldn't be a pretty hack (then one function can produce a different output depending on the context!).

Would it be possible for the user to call something like `full(Rep.image)` for instance?

Alternatively, if you see a way of 'getting the best of both worlds' as you say, by carefully splitting between which code should deal with full or sparse matrices, maybe it would be an option worth considering!

**Comment by denisrosset** [comment]
Regarding your first point: the barrier of entry should be as low as possible, without additional baggage to learn. This is why we store permutations as double row vectors, use cell arrays for direct product elements, etc..., whereas other data structures would be more efficient and probably easier for advanced users.

The other problem with sparse is the unpredictability. Storing everything with sparse would be way slower, so right now their use (when the flag is on) is mostly heuristic: constructing an identity matrix -> sparse, a permutation representation -> sparse, everything else? dense, or keep the same as the user input

Should we remove sparse entirely, or keep it only inside methods, or as input/output to private/protected methods?

To my understanding, sparse matrices are useful in a few cases:

- when describing SDP data (but that's outside RepLAB core mandate and can be special cased),
- when describing monomial, or representations that are particularly sparse (like the Specht basis for the symmetric group irreps). For that we can have a `RepBySparseImages` that ensures that the storage and application uses sparse matrices, while `rep.image` returns the full one.
- when using/storing block-diagonal representations.

Anyway, it's unlikely that we are using sparse matrices to store matrices that would not fit in memory as dense matrices.

Double floating point precision restricts us, probably, to problems in the 15000 x 15000 range, where dense storage is not an issue at the user interface (internally, it's another story of course, and we can optimize for that).

**Comment by denisrosset** [comment]
I propose the following:

1. Replace the `useSparse` with a `sparseCutoff` dimension value that forces matrices of small dimension to be dense, and let matrices of larger dimension to be stored as sparse when appropriate. That's a minimal code change, and I started a PR for that. Won't merge this one before we discuss.

2. Remove all uses of sparse matrices in the API. Introduce dedicated classes for sparse matrices for optimization purposes (so advanced users can look for that and use it, while beginners remain blissfully unaware of CSR vs. CSC storage etc)

**Comment by jdbancal** [comment]
From the initial post `this makes things like ComplexReflectionGroupTest much much slower` (https://github.com/replab/replab/issues/94#issue-495481014), I get the impression that this is not only a rare case problem but something quite concrete. Am I wrong?

**Comment by denisrosset** [comment]
That's a very concrete problem and it makes the computation of the commutant scale like `O(f(d)^2)` instead of `O(f(d))` for permutation representation, where `d` is the dimension.

(I changed the issue title because the root question is the use of sparse matrices in RepLAB, and whatever we do needs to be documented)

**Comment by jdbancal** [comment]
If this issue has concrete consequences, I'ld prefer to not give up the performance that we already have with sparse matrices: this is not about optimizing something further, but about not loosing something which works well. So I guess this means using sparse matrices where we think it makes sense, at least internally.

If at the same time relying on the user transforming outputs into their full form is a no go, then we'll need to make some kind of tradeoff.

From the current discussion, the tradeoffs I see are:
 1. Introduce a size cut-off above which sparse matrices are used. This would not entirely preserve users from encountering sparse matrices, but should do the job for beginners.
 2. Having specialized methods that the user can choose to benefit from sparse performance. This requires the user to be aware of these methods and to actively choose to use them in order to optimize his code. I don't find it very user-friendly: matrix multiplication libraries choose for their users, whether beginners or advances, which method to use, ideally we should liberate the user from this worry as well.
 3. Using specific methods for inner computations and having methods return dense matrices always, as you proposed.

Options 1 and 3 seem more in agreement with our philosophy. How would you estimate the added level of complexity and scalability for each of them?

**Comment by denisrosset** [comment]
For 1, see #96 . Complexity currently reduces.

For the future, I agree with 2 and 3.

Regarding the user experience:

I'd have specialized classes such as `RepBySparseImages`, and we switch internally to those as often as possible (test at construction time, by default for permutation representations, etc.). Those specialized classes nevertheless return dense matrices for explicit image computation; however, internal computations are optimized; at the same time, those specialized classes could propose additional methods to return sparse matrices directly as part of additional API.

Impact on usage complexity is minimal; we use OO inheritance and our specialized objects are valid `replab.Rep` instances. The contract of `Rep.image` states that dense matrices are returned and this is fulfilled. On the other hand, we'll specialize the action of a `replab.Rep` instance on a matrix by doing sparse matrix multiplication.

Impact on code complexity is low but there: this will add another implementation of `RepByImages`. No additional methods need to be added to implement the fast path, as we already use a different method to act on matrices with the representation.

And this is part of scalability: Later, we'll want specialized methods to construct Equivariant spaces for monomial representations. (We had that code in a preliminary version of RepLAB for commutants, but it hasn't been ported and generalized to Equivariant). The code support for multiple dispatch is already there, so no new abstractions are necessary.

**Comment by denisrosset** [comment]
Just thought of it: sparse and dense matrices are nearly interchangeable, except that sparse matrices do not support more than 2 dimensions. So we do not want to exhibit surprising behavior in the API. Solution 1 is clearly a bad idea in that respect.

**Comment by jdbancal** [comment]
Errh... I don't understand: do you mean that we cannot use sparse arrays because we'll need to deal with multi-dimensional arrays? If this is so, then even this issue should be closed.

Otherwise, if it's about the user interacting with the library, then I'm not sure we should worry about it too much: if we are not going to deal with multi-dimensional representations ourselves, we can fairly assume that most users also probably won't. Plus, with a threshold at 20, beginners will not see sparse arrays, but other people will be aware that images are typically sparse. And of course we should mention it in the doc, that images can be 2-D full or sparse arrays depending on the size. I agree that this is not fully ideal, but we are looking for a tradeoff.

Hence, there might be a better long-term solution than option 1, but given the simplicity of your suggestion #96 , I wouldn't discard it for this reason: my understanding is that it may give some troubles in rare situations (not even wrong results, rather a bit more work for the user), but would still give a clear improvement most of the time.

**Comment by denisrosset** [comment]
The problem with sparse arrays is that we can never give guarantees of where a sparse result will pop up. A lot of people in quantum info reshape and permute the hell out of stuff, so something that works for d=20 could suddenly break at d=21 and I don't want that kind of instability (which was a bit of my experience with old GAP system packages, things break in the middle of code and you don't have the knowledge to fix it).

Nevertheless, sparse matrices are a useful speedup at key points of our algorithm. I'll make sure they can be used in a controlled way.

**Comment by jdbancal** [comment]
Ok, so from what I read it seems that the reshaping stuff is not foreseen to happen in our code. Just to clarify, this mean that the code which could eventually break down is not the library code, but user code. This, of course, is still an undesirable thing, but I would not go all the way to blame ourselves for errors in the code of users who didn't read the documentation...

Would mentioning in the documentation that images in dimension <= 20 (or as given by the value of sparseCutoff) are full, and sparse in larger dimensions be a sufficiently clear statement of our treatment rules? (this would include in particular making this info appear when the user types `help functionName`).

Regarding options 2 and 3, thanks for the details in https://github.com/replab/replab/issues/94#issuecomment-533215365 . It is not clear to me, however, which part applies to option 2, and which part applies to option 3, do you think it would be possible to mention that in the comment?

**Comment by denisrosset** [comment]
I had safeguards in the eigenvalue decomposition algorithm to force dense matrices, as the behaviour changes between sparse and dense, see https://github.com/replab/replab/blob/2db072544e8284faf54660d20a067acff747c766/src/%2Breplab/%2Brep/decomposeUsingCommutant.m

Right now when cleaning up representation decomposition, I default to dense matrices by default; I'm profiling code, and introducing sparse matrices where they make sense, and document the API in that respect. For example, sparsity is very important for subrepresentations, because that's how we decompose intransitive representations (the ones where the action is already block diagonal, for example NPA with correlators). So `replab.SubRep` supports sparsity in the `decomposedispatch` branch.

**Comment by denisrosset** [comment]
I suggest we reintroduce sparsity where we pay the price. It leads to fragile and sometimes surprising behaviour. To accelerate decomposition of permutations for example, there are optimizations that are robust and faster than sparse multiplication (the row-column orbit enumeration algorithm).

From my perspective, it's difficult to speak of the advantages of different approaches when we don't have a clean baseline to start experimenting on.

**Comment by jdbancal** [comment]
As you wish, so if I understand, the current focus is on stability first

**Comment by denisrosset** [comment]
Not going out of my way to ban sparse matrices, so if the users provides sparse matrices, most things should work fine (but buyer beware!). I'm applying them in controlled areas first.

**Comment by denisrosset** [comment]
Sparse matrices are now explicitly used for the bases of subrepresentations, the code is documented as such, and care is taken to not propagate sparsity out of the internal computations.

@jdbancal Should we come back to this issue the next time we meet, and discuss it more in depth? Or close the issue, and wait until we stumble upon large scale problems that would benefit from sparsity?

**Comment by jdbancal** [comment]
Let's close this issue since a solution is now implemented. If needed, we can reopen the discussion, possibly with new elements in mind, when we'll deal with performance optimization.
